### ISSUE TITLE
[BORK] Player nicknames keep resetting and losing their color

### ISSUE THREAD

**Issue by Eutherin** [AuroraInteractive/network-script-data#20]
> **Describe the bug**:
Nick colors don't save

> **How To Reproduce**:
give yourself a nick, wait a bit after logging out, poof.

> **Expected behavior**:
nick should stay

> **Additional context**:
RIP my sweet sweet teal name :(

**Comment by BehrRiley** [comment]
After viewing your playerdata, it *is* actually evident your data was saved:
```yml
Tab_Display_name: '#004242E#006c70u#007f80t#009a9ch#009a9ce#007f80r#006c70i#004242n'
Display_Name: §x§0§0§4§2§4§2E§x§0§0§6§c§7§0u§x§0§0§7§f§8§0t§x§0§0§9§a§9§ch§x§0§0§9§a§9§ce§x§0§0§7§f§8§0r§x§0§0§6§c§7§0i§x§0§0§4§2§4§2n
rank: §x§7§5§7§6§7§6H§x§f§d§c§f§5§8E§x§f§2§7§d§0§cA§x§f§0§7§f§1§3D §x§7§3§0§8§0§8A§x§8§0§0§9§0§9R§x§8§0§0§9§0§9S§x§7§3§0§8§0§8O§x§f§0§7§f§1§3N§x§f§2§7§d§0§cI§x§f§d§c§f§5§8S§x§7§5§7§6§7§6T
```
Noticing also that BehrCraft is using TAB and Survival+ is not, can you verify if this is resolved on BehrCraft?
